### ISSUE TITLE
select menu icon error

### ISSUE THREAD

**Issue by DWelter24** [ArgoZhang/BootstrapAdmin#9]
when trying to select an icon for a menu item, page fails with this error message.

Failed to resolve module specifier 'Components/FAIconList.razor.js' TypeError: Failed to resolve module specifier 'Components/FAIconList.razor.js' at http://localhost:5210/_framework/blazor.server.js:1:940 at http://localhost:5210/_framework/blazor.server.js:1:3047 at new Promise () at y.beginInvokeJSFromDotNet (http://localhost:5210/_framework/blazor.server.js:1:3004) at Xt._invokeClientMethod (http://localhost:5210/_framework/blazor.server.js:1:60890) at Xt._processIncomingData (http://localhost:5210/_framework/blazor.server.js:1:58279) at Xt.connection.onreceive (http://localhost:5210/_framework/blazor.server.js:1:51920) at s.onmessage (http://localhost:5210/_framework/blazor.server.js:1:80026)

the online version, https://admin.blazor.zone/Admin/Menus, seems to work correctly.

**Comment by ArgoZhang** [comment]
@DWelter24 sure. i will fix this later.

**Comment by ArgoZhang** [comment]
@DWelter24 sorry for the delayed reply. this issue has been fixed. please pull t he latest version from the master branch.
